### ISSUE TITLE
Couldn't load plugin with pylintrc.ini 

### ISSUE THREAD

**Issue by md1023** [edaniszewski/pylint-quotes#12]
```
load-plugins=pylint_quotes
```
has no effect when put into `pylintrc.ini`, instead I have to call `load-plugins` every time:
```
pylint --rcfile=pylintrc.ini --load-plugins pylint_quotes api
```

**Comment by md1023** [comment]
Right, it was not under [MASTER] section. Sorry and thanks!

**Comment by edaniszewski** [comment]
No problem! Thanks for testing it out and verifying!
