### ISSUE TITLE
Pass `col_offset` when calls `add_message`

### ISSUE THREAD

**Issue by piotrgredowski** [edaniszewski/pylint-quotes#14]
It will be useful if `col_offset` ([link](https://github.com/PyCQA/pylint/blob/e1fdcce71d331130020a74f922728f4ca998e070/pylint/checkers/__init__.py#L107)) of found invalid quote is passed further to `self.add_message`. For example VSCode can then guide you (with F8 button) to specified column to fix issue reported.

**Comment by edaniszewski** [comment]
Thanks for the feedback -- this should now be implemented in version 0.2.0 which should be up on pypi now

**Comment by piotrgredowski** [comment]
Thanks! Everything works great :).
