### ISSUE TITLE
Improperly flags invalid-string-quote when embedding quotes in string

### ISSUE THREAD

**Issue by marcoceppi** [edaniszewski/pylint-quotes#21]
When producing a string like:

```
var = "'quoted text' should be 'singled'"
```

I get the follwoing

> Invalid string quote ", should be ' (invalid-string-quote)

Error

**Comment by edaniszewski** [comment]
@marcoceppi  What configuration were you running with? This sounds right to me as a default behavior where the checker is strict. You could try [configuring](https://github.com/edaniszewski/pylint-quotes#configuration) with `single-quote=single-avoid-escape` which should loosen the constraints when there are embedded quotes. I think that may fix this error

**Comment by marcoceppi** [comment]
That seems to help, thanks!

**Comment by edaniszewski** [comment]
I'll update docs to make this more clear -- thanks for opening the issue (:
